/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package cz.davidkurzica.contract.models


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializer
import kotlinx.serialization.builtins.serializer
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder

/**
 * 
 *
 * Values: DATE_TIME,FROM,TO,VIA,UNKNOWN_DEFAULT_OPEN_API
 */
@Serializable(with = InputFieldSerializer::class)
enum class InputField(val value: kotlin.String) {

    @SerialName(value = "DATE_TIME")
    DATE_TIME("DATE_TIME"),

    @SerialName(value = "FROM")
    FROM("FROM"),

    @SerialName(value = "TO")
    TO("TO"),

    @SerialName(value = "VIA")
    VIA("VIA"),

    @SerialName(value = "unknown_default_open_api")
    UNKNOWN_DEFAULT_OPEN_API("unknown_default_open_api");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is InputField) "$data" else null

        /**
         * Returns a valid [InputField] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): InputField? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

internal object InputFieldSerializer : KSerializer<InputField> {
    override val descriptor = kotlin.String.serializer().descriptor

    override fun deserialize(decoder: Decoder): InputField {
        val value = decoder.decodeSerializableValue(kotlin.String.serializer())
        return InputField.values().firstOrNull { it.value == value }
            ?: InputField.UNKNOWN_DEFAULT_OPEN_API
    }

    override fun serialize(encoder: Encoder, value: InputField) {
        encoder.encodeSerializableValue(kotlin.String.serializer(), value.value)
    }
}

