/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package cz.davidkurzica.contract.models

import cz.davidkurzica.contract.models.Leg

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual
import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializer
import kotlinx.serialization.builtins.serializer
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder

/**
 * 
 *
 * @param numberOfTransfers 
 * @param legs 
 * @param start 
 * @param end 
 * @param duration 
 * @param waitingTime 
 * @param accessibilityScore 
 */
@Serializable

data class Itinerary (

    @SerialName(value = "numberOfTransfers")
    val numberOfTransfers: kotlin.Int,

    @SerialName(value = "legs")
    val legs: kotlin.collections.List<Leg>,

    @SerialName(value = "start")
    val start: kotlin.String? = null,

    @SerialName(value = "end")
    val end: kotlin.String? = null,

    @SerialName(value = "duration")
    val duration: kotlin.Long? = null,

    @SerialName(value = "waitingTime")
    val waitingTime: kotlin.Long? = null,

    @SerialName(value = "accessibilityScore")
    val accessibilityScore: kotlin.Double? = null

) {


}

