/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package cz.davidkurzica.contract.models

import cz.davidkurzica.contract.models.LegTime
import cz.davidkurzica.contract.models.Mode
import cz.davidkurzica.contract.models.Place
import cz.davidkurzica.contract.models.PlanConnectionGeometry
import cz.davidkurzica.contract.models.PlanConnectionRoute
import cz.davidkurzica.contract.models.PlanConnectionTrip

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual
import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializer
import kotlinx.serialization.builtins.serializer
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder

/**
 * 
 *
 * @param start 
 * @param end 
 * @param from 
 * @param to 
 * @param mode 
 * @param route 
 * @param headsign 
 * @param distance 
 * @param duration 
 * @param accessibilityScore 
 * @param trip 
 * @param legGeometry 
 */
@Serializable

data class Leg (

    @SerialName(value = "start")
    val start: LegTime,

    @SerialName(value = "end")
    val end: LegTime,

    @SerialName(value = "from")
    val from: Place,

    @SerialName(value = "to")
    val to: Place,

    @Contextual @SerialName(value = "mode")
    val mode: Mode? = null,

    @SerialName(value = "route")
    val route: PlanConnectionRoute? = null,

    @SerialName(value = "headsign")
    val headsign: kotlin.String? = null,

    @SerialName(value = "distance")
    val distance: kotlin.Double? = null,

    @SerialName(value = "duration")
    val duration: kotlin.Double? = null,

    @SerialName(value = "accessibilityScore")
    val accessibilityScore: kotlin.Double? = null,

    @SerialName(value = "trip")
    val trip: PlanConnectionTrip? = null,

    @SerialName(value = "legGeometry")
    val legGeometry: PlanConnectionGeometry? = null

) {


}

