/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package cz.davidkurzica.contract.models


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializer
import kotlinx.serialization.builtins.serializer
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder

/**
 * 
 *
 * Values: AIRPLANE,BICYCLE,BUS,CABLE_CAR,CAR,CARPOOL,COACH,FERRY,FLEX,FLEXIBLE,FUNICULAR,GONDOLA,LEG_SWITCH,MONORAIL,RAIL,SCOOTER,SUBWAY,TAXI,TRAM,TRANSIT,TROLLEYBUS,WALK,UNKNOWN_DEFAULT_OPEN_API
 */
@Serializable(with = ModeSerializer::class)
enum class Mode(val value: kotlin.String) {

    @SerialName(value = "AIRPLANE")
    AIRPLANE("AIRPLANE"),

    @SerialName(value = "BICYCLE")
    BICYCLE("BICYCLE"),

    @SerialName(value = "BUS")
    BUS("BUS"),

    @SerialName(value = "CABLE_CAR")
    CABLE_CAR("CABLE_CAR"),

    @SerialName(value = "CAR")
    CAR("CAR"),

    @SerialName(value = "CARPOOL")
    CARPOOL("CARPOOL"),

    @SerialName(value = "COACH")
    COACH("COACH"),

    @SerialName(value = "FERRY")
    FERRY("FERRY"),

    @SerialName(value = "FLEX")
    FLEX("FLEX"),

    @SerialName(value = "FLEXIBLE")
    FLEXIBLE("FLEXIBLE"),

    @SerialName(value = "FUNICULAR")
    FUNICULAR("FUNICULAR"),

    @SerialName(value = "GONDOLA")
    GONDOLA("GONDOLA"),

    @SerialName(value = "LEG_SWITCH")
    LEG_SWITCH("LEG_SWITCH"),

    @SerialName(value = "MONORAIL")
    MONORAIL("MONORAIL"),

    @SerialName(value = "RAIL")
    RAIL("RAIL"),

    @SerialName(value = "SCOOTER")
    SCOOTER("SCOOTER"),

    @SerialName(value = "SUBWAY")
    SUBWAY("SUBWAY"),

    @SerialName(value = "TAXI")
    TAXI("TAXI"),

    @SerialName(value = "TRAM")
    TRAM("TRAM"),

    @SerialName(value = "TRANSIT")
    TRANSIT("TRANSIT"),

    @SerialName(value = "TROLLEYBUS")
    TROLLEYBUS("TROLLEYBUS"),

    @SerialName(value = "WALK")
    WALK("WALK"),

    @SerialName(value = "unknown_default_open_api")
    UNKNOWN_DEFAULT_OPEN_API("unknown_default_open_api");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is Mode) "$data" else null

        /**
         * Returns a valid [Mode] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): Mode? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

internal object ModeSerializer : KSerializer<Mode> {
    override val descriptor = kotlin.String.serializer().descriptor

    override fun deserialize(decoder: Decoder): Mode {
        val value = decoder.decodeSerializableValue(kotlin.String.serializer())
        return Mode.values().firstOrNull { it.value == value }
            ?: Mode.UNKNOWN_DEFAULT_OPEN_API
    }

    override fun serialize(encoder: Encoder, value: Mode) {
        encoder.encodeSerializableValue(kotlin.String.serializer(), value.value)
    }
}

