/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package cz.davidkurzica.contract.models

import cz.davidkurzica.contract.models.PlanConnectionVariables

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual
import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializer
import kotlinx.serialization.builtins.serializer
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder

/**
 * 
 *
 * @param id Persisted-query id (lowercase hex SHA-256 of the canonical query).
 * @param variables 
 */
@Serializable

data class PlanConnectionRequest (

    /* Persisted-query id (lowercase hex SHA-256 of the canonical query). */
    @SerialName(value = "id")
    val id: PlanConnectionRequest.Id,

    @SerialName(value = "variables")
    val variables: PlanConnectionVariables

) {

    /**
     * Persisted-query id (lowercase hex SHA-256 of the canonical query).
     *
     * Values: F19608964D423831B485CCC878CB25EFF56C720585D4423EE617C864E2B3102E,UNKNOWN_DEFAULT_OPEN_API
     */
    @Serializable(with = IdSerializer::class)
    enum class Id(val value: kotlin.String) {
        @SerialName(value = "f19608964d423831b485ccc878cb25eff56c720585d4423ee617c864e2b3102e") F19608964D423831B485CCC878CB25EFF56C720585D4423EE617C864E2B3102E("f19608964d423831b485ccc878cb25eff56c720585d4423ee617c864e2b3102e"),
        @SerialName(value = "unknown_default_open_api") UNKNOWN_DEFAULT_OPEN_API("unknown_default_open_api");
    }

    internal object IdSerializer : KSerializer<Id> {
        override val descriptor = kotlin.String.serializer().descriptor

        override fun deserialize(decoder: Decoder): Id {
            val value = decoder.decodeSerializableValue(kotlin.String.serializer())
            return Id.values().firstOrNull { it.value == value }
                ?: Id.UNKNOWN_DEFAULT_OPEN_API
        }

        override fun serialize(encoder: Encoder, value: Id) {
            encoder.encodeSerializableValue(kotlin.String.serializer(), value.value)
        }
    }

}

