/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package cz.davidkurzica.contract.models

import cz.davidkurzica.contract.models.GraphQLError
import cz.davidkurzica.contract.models.PlanConnectionData

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual
import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializer
import kotlinx.serialization.builtins.serializer
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder

/**
 * 
 *
 * @param `data` 
 * @param errors 
 */
@Serializable

data class PlanConnectionResponse (

    @SerialName(value = "data")
    val `data`: PlanConnectionData? = null,

    @SerialName(value = "errors")
    val errors: kotlin.collections.List<GraphQLError>? = null

) {


}

