/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package cz.davidkurzica.contract.models

import cz.davidkurzica.contract.models.PlanCoordinateInput

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual
import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializer
import kotlinx.serialization.builtins.serializer
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder

/**
 * 
 *
 * @param coordinate 
 * @param label 
 * @param minimumWaitTime 
 * @param stopLocationIds 
 */
@Serializable

data class PlanVisitViaLocationInput (

    @SerialName(value = "coordinate")
    val coordinate: PlanCoordinateInput? = null,

    @SerialName(value = "label")
    val label: kotlin.String? = null,

    @SerialName(value = "minimumWaitTime")
    val minimumWaitTime: kotlin.String? = null,

    @SerialName(value = "stopLocationIds")
    val stopLocationIds: kotlin.collections.List<kotlin.String>? = null

) {


}

