/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package cz.davidkurzica.contract.models

import cz.davidkurzica.contract.models.PlanEdge
import cz.davidkurzica.contract.models.PlanPageInfo
import cz.davidkurzica.contract.models.RoutingError

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual
import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializer
import kotlinx.serialization.builtins.serializer
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder

/**
 * 
 *
 * @param pageInfo 
 * @param routingErrors 
 * @param edges 
 * @param searchDateTime 
 */
@Serializable

data class PlanConnection (

    @SerialName(value = "pageInfo")
    val pageInfo: PlanPageInfo,

    @SerialName(value = "routingErrors")
    val routingErrors: kotlin.collections.List<RoutingError>,

    @SerialName(value = "edges")
    val edges: kotlin.collections.List<PlanEdge>? = null,

    @SerialName(value = "searchDateTime")
    val searchDateTime: kotlin.String? = null

) {


}

