/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package cz.davidkurzica.contract.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual
import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializer
import kotlinx.serialization.builtins.serializer
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder

/**
 * 
 *
 * @param hasNextPage 
 * @param hasPreviousPage 
 * @param startCursor 
 * @param endCursor 
 * @param searchWindowUsed 
 */
@Serializable

data class PlanPageInfo (

    @SerialName(value = "hasNextPage")
    val hasNextPage: kotlin.Boolean,

    @SerialName(value = "hasPreviousPage")
    val hasPreviousPage: kotlin.Boolean,

    @SerialName(value = "startCursor")
    val startCursor: kotlin.String? = null,

    @SerialName(value = "endCursor")
    val endCursor: kotlin.String? = null,

    @SerialName(value = "searchWindowUsed")
    val searchWindowUsed: kotlin.String? = null

) {


}

