/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package cz.davidkurzica.contract.models

import cz.davidkurzica.contract.models.PlanDateTimeInput
import cz.davidkurzica.contract.models.PlanLabeledLocationInput
import cz.davidkurzica.contract.models.PlanViaLocationInput

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual
import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializer
import kotlinx.serialization.builtins.serializer
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder

/**
 * 
 *
 * @param dateTime 
 * @param origin 
 * @param destination 
 * @param via 
 * @param first 
 * @param before 
 * @param after 
 */
@Serializable

data class PlanConnectionVariables (

    @SerialName(value = "dateTime")
    val dateTime: PlanDateTimeInput,

    @SerialName(value = "origin")
    val origin: PlanLabeledLocationInput,

    @SerialName(value = "destination")
    val destination: PlanLabeledLocationInput,

    @SerialName(value = "via")
    val via: kotlin.collections.List<PlanViaLocationInput>? = null,

    @SerialName(value = "first")
    val first: kotlin.Int? = null,

    @SerialName(value = "before")
    val before: kotlin.String? = null,

    @SerialName(value = "after")
    val after: kotlin.String? = null

) {


}

