/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package cz.davidkurzica.contract.models

import cz.davidkurzica.contract.models.Itinerary

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual
import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializer
import kotlinx.serialization.builtins.serializer
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder

/**
 * 
 *
 * @param cursor 
 * @param node 
 */
@Serializable

data class PlanEdge (

    @SerialName(value = "cursor")
    val cursor: kotlin.String,

    @SerialName(value = "node")
    val node: Itinerary

) {


}

