/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package cz.davidkurzica.contract.models

import cz.davidkurzica.contract.models.PlanPassThroughViaLocationInput
import cz.davidkurzica.contract.models.PlanVisitViaLocationInput

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual
import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializer
import kotlinx.serialization.builtins.serializer
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder

/**
 * 
 *
 * @param passThrough 
 * @param visit 
 */
@Serializable

data class PlanViaLocationInput (

    @SerialName(value = "passThrough")
    val passThrough: PlanPassThroughViaLocationInput? = null,

    @SerialName(value = "visit")
    val visit: PlanVisitViaLocationInput? = null

) {


}

