/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package cz.davidkurzica.contract.models

import cz.davidkurzica.contract.models.PlanCoordinateInput
import cz.davidkurzica.contract.models.PlanStopLocationInput

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual
import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializer
import kotlinx.serialization.builtins.serializer
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder

/**
 * 
 *
 * @param coordinate 
 * @param stopLocation 
 */
@Serializable

data class PlanLocationInput (

    @SerialName(value = "coordinate")
    val coordinate: PlanCoordinateInput? = null,

    @SerialName(value = "stopLocation")
    val stopLocation: PlanStopLocationInput? = null

) {


}

