/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package cz.davidkurzica.contract.models


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializer
import kotlinx.serialization.builtins.serializer
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder

/**
 * 
 *
 * Values: ADDED,CANCELED,MODIFIED,SCHEDULED,UPDATED,UNKNOWN_DEFAULT_OPEN_API
 */
@Serializable(with = RealtimeStateSerializer::class)
enum class RealtimeState(val value: kotlin.String) {

    @SerialName(value = "ADDED")
    ADDED("ADDED"),

    @SerialName(value = "CANCELED")
    CANCELED("CANCELED"),

    @SerialName(value = "MODIFIED")
    MODIFIED("MODIFIED"),

    @SerialName(value = "SCHEDULED")
    SCHEDULED("SCHEDULED"),

    @SerialName(value = "UPDATED")
    UPDATED("UPDATED"),

    @SerialName(value = "unknown_default_open_api")
    UNKNOWN_DEFAULT_OPEN_API("unknown_default_open_api");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is RealtimeState) "$data" else null

        /**
         * Returns a valid [RealtimeState] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): RealtimeState? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

internal object RealtimeStateSerializer : KSerializer<RealtimeState> {
    override val descriptor = kotlin.String.serializer().descriptor

    override fun deserialize(decoder: Decoder): RealtimeState {
        val value = decoder.decodeSerializableValue(kotlin.String.serializer())
        return RealtimeState.values().firstOrNull { it.value == value }
            ?: RealtimeState.UNKNOWN_DEFAULT_OPEN_API
    }

    override fun serialize(encoder: Encoder, value: RealtimeState) {
        encoder.encodeSerializableValue(kotlin.String.serializer(), value.value)
    }
}

