/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package cz.davidkurzica.contract.models

import cz.davidkurzica.contract.models.InputField
import cz.davidkurzica.contract.models.RoutingErrorCode

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual
import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializer
import kotlinx.serialization.builtins.serializer
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder

/**
 * 
 *
 * @param code 
 * @param description 
 * @param inputField 
 */
@Serializable

data class RoutingError (

    @Contextual @SerialName(value = "code")
    val code: RoutingErrorCode,

    @SerialName(value = "description")
    val description: kotlin.String,

    @Contextual @SerialName(value = "inputField")
    val inputField: InputField? = null

) {


}

