/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package cz.davidkurzica.contract.models

import cz.davidkurzica.contract.models.TransitMode

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual
import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializer
import kotlinx.serialization.builtins.serializer
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder

/**
 * 
 *
 * @param shortName 
 * @param longName 
 * @param mode 
 */
@Serializable

data class Route (

    @SerialName(value = "shortName")
    val shortName: kotlin.String? = null,

    @SerialName(value = "longName")
    val longName: kotlin.String? = null,

    @Contextual @SerialName(value = "mode")
    val mode: TransitMode? = null

) {


}

