/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package cz.davidkurzica.contract.models


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializer
import kotlinx.serialization.builtins.serializer
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder

/**
 * 
 *
 * Values: LOCATION_NOT_FOUND,NO_STOPS_IN_RANGE,NO_TRANSIT_CONNECTION,NO_TRANSIT_CONNECTION_IN_SEARCH_WINDOW,OUTSIDE_BOUNDS,OUTSIDE_SERVICE_PERIOD,WALKING_BETTER_THAN_TRANSIT,UNKNOWN_DEFAULT_OPEN_API
 */
@Serializable(with = RoutingErrorCodeSerializer::class)
enum class RoutingErrorCode(val value: kotlin.String) {

    @SerialName(value = "LOCATION_NOT_FOUND")
    LOCATION_NOT_FOUND("LOCATION_NOT_FOUND"),

    @SerialName(value = "NO_STOPS_IN_RANGE")
    NO_STOPS_IN_RANGE("NO_STOPS_IN_RANGE"),

    @SerialName(value = "NO_TRANSIT_CONNECTION")
    NO_TRANSIT_CONNECTION("NO_TRANSIT_CONNECTION"),

    @SerialName(value = "NO_TRANSIT_CONNECTION_IN_SEARCH_WINDOW")
    NO_TRANSIT_CONNECTION_IN_SEARCH_WINDOW("NO_TRANSIT_CONNECTION_IN_SEARCH_WINDOW"),

    @SerialName(value = "OUTSIDE_BOUNDS")
    OUTSIDE_BOUNDS("OUTSIDE_BOUNDS"),

    @SerialName(value = "OUTSIDE_SERVICE_PERIOD")
    OUTSIDE_SERVICE_PERIOD("OUTSIDE_SERVICE_PERIOD"),

    @SerialName(value = "WALKING_BETTER_THAN_TRANSIT")
    WALKING_BETTER_THAN_TRANSIT("WALKING_BETTER_THAN_TRANSIT"),

    @SerialName(value = "unknown_default_open_api")
    UNKNOWN_DEFAULT_OPEN_API("unknown_default_open_api");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is RoutingErrorCode) "$data" else null

        /**
         * Returns a valid [RoutingErrorCode] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): RoutingErrorCode? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

internal object RoutingErrorCodeSerializer : KSerializer<RoutingErrorCode> {
    override val descriptor = kotlin.String.serializer().descriptor

    override fun deserialize(decoder: Decoder): RoutingErrorCode {
        val value = decoder.decodeSerializableValue(kotlin.String.serializer())
        return RoutingErrorCode.values().firstOrNull { it.value == value }
            ?: RoutingErrorCode.UNKNOWN_DEFAULT_OPEN_API
    }

    override fun serialize(encoder: Encoder, value: RoutingErrorCode) {
        encoder.encodeSerializableValue(kotlin.String.serializer(), value.value)
    }
}

