/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package cz.davidkurzica.contract.models

import cz.davidkurzica.contract.models.Stoptime
import cz.davidkurzica.contract.models.WheelchairBoarding

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual
import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializer
import kotlinx.serialization.builtins.serializer
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder

/**
 * 
 *
 * @param gtfsId 
 * @param name 
 * @param wheelchairBoarding 
 * @param stoptimesWithoutPatterns 
 */
@Serializable

data class Stop (

    @SerialName(value = "gtfsId")
    val gtfsId: kotlin.String,

    @SerialName(value = "name")
    val name: kotlin.String,

    @Contextual @SerialName(value = "wheelchairBoarding")
    val wheelchairBoarding: WheelchairBoarding? = null,

    @SerialName(value = "stoptimesWithoutPatterns")
    val stoptimesWithoutPatterns: kotlin.collections.List<Stoptime>? = null

) {


}

