/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package cz.davidkurzica.contract.models

import cz.davidkurzica.contract.models.StopDeparturesVariables

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual
import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializer
import kotlinx.serialization.builtins.serializer
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder

/**
 * 
 *
 * @param id Persisted-query id (lowercase hex SHA-256 of the canonical query).
 * @param variables 
 */
@Serializable

data class StopDeparturesRequest (

    /* Persisted-query id (lowercase hex SHA-256 of the canonical query). */
    @SerialName(value = "id")
    val id: StopDeparturesRequest.Id,

    @SerialName(value = "variables")
    val variables: StopDeparturesVariables

) {

    /**
     * Persisted-query id (lowercase hex SHA-256 of the canonical query).
     *
     * Values: _70A644FE3C6B2CBF5B2D70CEF8230C1428BEA6357AE1766772162D86469563D0,UNKNOWN_DEFAULT_OPEN_API
     */
    @Serializable(with = IdSerializer::class)
    enum class Id(val value: kotlin.String) {
        @SerialName(value = "70a644fe3c6b2cbf5b2d70cef8230c1428bea6357ae1766772162d86469563d0") _70A644FE3C6B2CBF5B2D70CEF8230C1428BEA6357AE1766772162D86469563D0("70a644fe3c6b2cbf5b2d70cef8230c1428bea6357ae1766772162d86469563d0"),
        @SerialName(value = "unknown_default_open_api") UNKNOWN_DEFAULT_OPEN_API("unknown_default_open_api");
    }

    internal object IdSerializer : KSerializer<Id> {
        override val descriptor = kotlin.String.serializer().descriptor

        override fun deserialize(decoder: Decoder): Id {
            val value = decoder.decodeSerializableValue(kotlin.String.serializer())
            return Id.values().firstOrNull { it.value == value }
                ?: Id.UNKNOWN_DEFAULT_OPEN_API
        }

        override fun serialize(encoder: Encoder, value: Id) {
            encoder.encodeSerializableValue(kotlin.String.serializer(), value.value)
        }
    }

}

