/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package cz.davidkurzica.contract.models

import cz.davidkurzica.contract.models.RealtimeState
import cz.davidkurzica.contract.models.Trip

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual
import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializer
import kotlinx.serialization.builtins.serializer
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder

/**
 * 
 *
 * @param serviceDay 
 * @param scheduledDeparture 
 * @param realtimeDeparture 
 * @param realtime 
 * @param realtimeState 
 * @param headsign 
 * @param trip 
 */
@Serializable

data class Stoptime (

    @SerialName(value = "serviceDay")
    val serviceDay: kotlin.Long? = null,

    @SerialName(value = "scheduledDeparture")
    val scheduledDeparture: kotlin.Int? = null,

    @SerialName(value = "realtimeDeparture")
    val realtimeDeparture: kotlin.Int? = null,

    @SerialName(value = "realtime")
    val realtime: kotlin.Boolean? = null,

    @Contextual @SerialName(value = "realtimeState")
    val realtimeState: RealtimeState? = null,

    @SerialName(value = "headsign")
    val headsign: kotlin.String? = null,

    @SerialName(value = "trip")
    val trip: Trip? = null

) {


}

