/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package cz.davidkurzica.contract.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual
import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializer
import kotlinx.serialization.builtins.serializer
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder

/**
 * 
 *
 * @param id 
 * @param numberOfDepartures 
 * @param startTime 
 * @param timeRange 
 */
@Serializable

data class StopDeparturesVariables (

    @SerialName(value = "id")
    val id: kotlin.String,

    @SerialName(value = "numberOfDepartures")
    val numberOfDepartures: kotlin.Int? = null,

    @SerialName(value = "startTime")
    val startTime: kotlin.Long? = null,

    @SerialName(value = "timeRange")
    val timeRange: kotlin.Int? = null

) {


}

