/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package cz.davidkurzica.contract.models


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializer
import kotlinx.serialization.builtins.serializer
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder

/**
 * 
 *
 * Values: AIRPLANE,BUS,CABLE_CAR,CARPOOL,COACH,FERRY,FUNICULAR,GONDOLA,MONORAIL,RAIL,SNOW_AND_ICE,SUBWAY,TAXI,TRAM,TROLLEYBUS,UNKNOWN_DEFAULT_OPEN_API
 */
@Serializable(with = TransitModeSerializer::class)
enum class TransitMode(val value: kotlin.String) {

    @SerialName(value = "AIRPLANE")
    AIRPLANE("AIRPLANE"),

    @SerialName(value = "BUS")
    BUS("BUS"),

    @SerialName(value = "CABLE_CAR")
    CABLE_CAR("CABLE_CAR"),

    @SerialName(value = "CARPOOL")
    CARPOOL("CARPOOL"),

    @SerialName(value = "COACH")
    COACH("COACH"),

    @SerialName(value = "FERRY")
    FERRY("FERRY"),

    @SerialName(value = "FUNICULAR")
    FUNICULAR("FUNICULAR"),

    @SerialName(value = "GONDOLA")
    GONDOLA("GONDOLA"),

    @SerialName(value = "MONORAIL")
    MONORAIL("MONORAIL"),

    @SerialName(value = "RAIL")
    RAIL("RAIL"),

    @SerialName(value = "SNOW_AND_ICE")
    SNOW_AND_ICE("SNOW_AND_ICE"),

    @SerialName(value = "SUBWAY")
    SUBWAY("SUBWAY"),

    @SerialName(value = "TAXI")
    TAXI("TAXI"),

    @SerialName(value = "TRAM")
    TRAM("TRAM"),

    @SerialName(value = "TROLLEYBUS")
    TROLLEYBUS("TROLLEYBUS"),

    @SerialName(value = "unknown_default_open_api")
    UNKNOWN_DEFAULT_OPEN_API("unknown_default_open_api");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is TransitMode) "$data" else null

        /**
         * Returns a valid [TransitMode] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): TransitMode? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

internal object TransitModeSerializer : KSerializer<TransitMode> {
    override val descriptor = kotlin.String.serializer().descriptor

    override fun deserialize(decoder: Decoder): TransitMode {
        val value = decoder.decodeSerializableValue(kotlin.String.serializer())
        return TransitMode.values().firstOrNull { it.value == value }
            ?: TransitMode.UNKNOWN_DEFAULT_OPEN_API
    }

    override fun serialize(encoder: Encoder, value: TransitMode) {
        encoder.encodeSerializableValue(kotlin.String.serializer(), value.value)
    }
}

