/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package cz.davidkurzica.contract.models

import cz.davidkurzica.contract.models.BikesAllowed
import cz.davidkurzica.contract.models.Geometry
import cz.davidkurzica.contract.models.Route
import cz.davidkurzica.contract.models.TripStoptime

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual
import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializer
import kotlinx.serialization.builtins.serializer
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder

/**
 * 
 *
 * @param gtfsId 
 * @param route 
 * @param directionId 
 * @param tripHeadsign 
 * @param bikesAllowed 
 * @param stoptimesForDate 
 * @param tripGeometry 
 */
@Serializable

data class TripTrip (

    @SerialName(value = "gtfsId")
    val gtfsId: kotlin.String,

    @SerialName(value = "route")
    val route: Route,

    @SerialName(value = "directionId")
    val directionId: kotlin.String? = null,

    @SerialName(value = "tripHeadsign")
    val tripHeadsign: kotlin.String? = null,

    @Contextual @SerialName(value = "bikesAllowed")
    val bikesAllowed: BikesAllowed? = null,

    @SerialName(value = "stoptimesForDate")
    val stoptimesForDate: kotlin.collections.List<TripStoptime>? = null,

    @SerialName(value = "tripGeometry")
    val tripGeometry: Geometry? = null

) {


}

