/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package cz.davidkurzica.contract.models

import cz.davidkurzica.contract.models.TripVariables

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual
import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializer
import kotlinx.serialization.builtins.serializer
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder

/**
 * 
 *
 * @param id Persisted-query id (lowercase hex SHA-256 of the canonical query).
 * @param variables 
 */
@Serializable

data class TripRequest (

    /* Persisted-query id (lowercase hex SHA-256 of the canonical query). */
    @SerialName(value = "id")
    val id: TripRequest.Id,

    @SerialName(value = "variables")
    val variables: TripVariables

) {

    /**
     * Persisted-query id (lowercase hex SHA-256 of the canonical query).
     *
     * Values: E8959A8D47A8E8437EE3EC740CD9C3E28BD401EFDD236DDE0502559DAEA53920,UNKNOWN_DEFAULT_OPEN_API
     */
    @Serializable(with = IdSerializer::class)
    enum class Id(val value: kotlin.String) {
        @SerialName(value = "e8959a8d47a8e8437ee3ec740cd9c3e28bd401efdd236dde0502559daea53920") E8959A8D47A8E8437EE3EC740CD9C3E28BD401EFDD236DDE0502559DAEA53920("e8959a8d47a8e8437ee3ec740cd9c3e28bd401efdd236dde0502559daea53920"),
        @SerialName(value = "unknown_default_open_api") UNKNOWN_DEFAULT_OPEN_API("unknown_default_open_api");
    }

    internal object IdSerializer : KSerializer<Id> {
        override val descriptor = kotlin.String.serializer().descriptor

        override fun deserialize(decoder: Decoder): Id {
            val value = decoder.decodeSerializableValue(kotlin.String.serializer())
            return Id.values().firstOrNull { it.value == value }
                ?: Id.UNKNOWN_DEFAULT_OPEN_API
        }

        override fun serialize(encoder: Encoder, value: Id) {
            encoder.encodeSerializableValue(kotlin.String.serializer(), value.value)
        }
    }

}

