/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package cz.davidkurzica.contract.models

import cz.davidkurzica.contract.models.RealtimeState
import cz.davidkurzica.contract.models.TripStop

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual
import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializer
import kotlinx.serialization.builtins.serializer
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder

/**
 * 
 *
 * @param serviceDay 
 * @param scheduledArrival 
 * @param scheduledDeparture 
 * @param realtimeArrival 
 * @param realtimeDeparture 
 * @param realtime 
 * @param realtimeState 
 * @param stop 
 */
@Serializable

data class TripStoptime (

    @SerialName(value = "serviceDay")
    val serviceDay: kotlin.Long? = null,

    @SerialName(value = "scheduledArrival")
    val scheduledArrival: kotlin.Int? = null,

    @SerialName(value = "scheduledDeparture")
    val scheduledDeparture: kotlin.Int? = null,

    @SerialName(value = "realtimeArrival")
    val realtimeArrival: kotlin.Int? = null,

    @SerialName(value = "realtimeDeparture")
    val realtimeDeparture: kotlin.Int? = null,

    @SerialName(value = "realtime")
    val realtime: kotlin.Boolean? = null,

    @Contextual @SerialName(value = "realtimeState")
    val realtimeState: RealtimeState? = null,

    @SerialName(value = "stop")
    val stop: TripStop? = null

) {


}

