query PlanConnection(
    $dateTime: PlanDateTimeInput!,
    $origin: PlanLabeledLocationInput!,
    $destination: PlanLabeledLocationInput!,
    $via: [PlanViaLocationInput!],
    $first: Int,
    $before: String,
    $after: String,
) {
    planConnection(
        dateTime: $dateTime,
        origin: $origin,
        destination: $destination,
        via: $via,
        first: $first,
        before: $before,
        after: $after,
    ) {
        edges {
            cursor
            node {
                start
                end
                duration
                waitingTime
                numberOfTransfers
                accessibilityScore
                legs {
                    mode
                    start { scheduledTime }
                    end { scheduledTime }
                    from { name stop { wheelchairBoarding } }
                    to { name stop { wheelchairBoarding } }
                    route { shortName longName }
                    headsign
                    distance
                    duration
                    accessibilityScore
                    trip { gtfsId bikesAllowed }
                    legGeometry { points }
                }
            }
        }
        pageInfo {
            startCursor
            endCursor
            hasNextPage
            hasPreviousPage
            searchWindowUsed
        }
        routingErrors {
            code
            description
            inputField
        }
        searchDateTime
    }
}
